on:
  push:
    tags:
      - 'v*.*.*'

name: Bundle Application

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      
    - name: Install FPM (for installer)
      run: |
        gem install fpm
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Freeze Application
      run: |
        ppg freeze --debug

    - name: Create Installer
      run: |
        ppg installer
        mv target/Waveform-Wizard.deb target/Waveform-Wizard_ubuntu-20_04.deb
      
    # - name: Create a Release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    #   with:
    #     tag_name: v1.0.0
    #     release_name: Release v1.0.0
    #     draft: false
    #     prerelease: false
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        token: ${{ secrets.RELEASE_TOKEN }}
        files: |
          target/Waveform-Wizard_ubuntu-20_04.deb
            
    # - name: Upload .deb to Release
    #   uses: actions/upload-release-asset@v1
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: target/Waveform-Wizard.deb
    #     asset_name: waveform-wizard-ubuntu-22.04.deb
    #     asset_content_type: application/octet-stream
  
    # - name: Save Deb file
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Ubuntu Installer
    #     path: target/Waveform-Wizard.deb
  
    # - name: Save Binary file
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Ubuntu Binary
    #     path: target/Waveform-Wizard/Waveform-Wizard
  
  build-windows:
    runs-on: windows-2019
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install FPM (for installer)
      run: gem install fpm
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Freeze Application
      run: ppg freeze --debug

    - name: Create Installer
      run: |
        ppg installer
        mv target/Waveform-WizardSetup.exe target/Waveform-Wizard-Setup_windows_10.exe
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        token: ${{ secrets.RELEASE_TOKEN }}
        files: |
          target/Waveform-Wizard-Setup_windows_10.exe
          
    # - name: Save Installer file
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Windows Installer
    #     path: target\Waveform-WizardSetup.exe
  
    # - name: Save Binary file
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Windows Binary
    #     path: target\Waveform-Wizard\Waveform-Wizard.exe
