on:
  workflow_dispatch:

name: Python CI

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.0'
      
    - name: Install FPM (for installer)
      run: |
        gem install fpm
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Freeze Application
      run: |
        ppg freeze

    - name: Create Installer
      run: |
        ppg installer

    - name: Save Deb file
      uses: actions/upload-artifact@v3
      with:
        name: Ubuntu Installer
        path: target/Waveform-Wizard.deb
  
    - name: Save Binary file
      uses: actions/upload-artifact@v3
      with:
        name: Ubuntu Binary
        path: target/Waveform-Wizard/Waveform-Wizard
  
  build-windows:
    runs-on: windows-2019
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install FPM (for installer)
      run: gem install fpm
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Freeze Application
      run: ppg freeze

    - name: Create Installer
      run: ppg installer

    - name: Save Installer file
      uses: actions/upload-artifact@v3
      with:
        name: Windows Installer
        path: target\Waveform-Wizard.exe
  
    - name: Save Binary file
      uses: actions/upload-artifact@v3
      with:
        name: Windows Binary
        path: target\Waveform-Wizard\Waveform-Wizard.exe
